name: freesms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.13.7+8

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  flutter_sms_inbox: ^1.0.2
  flutter_contacts: ^1.1.5
  permission_handler: ^10.2.0
  flutter_sms: ^2.3.3
  excel: 2.0.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  pretty_dio_logger: ^1.1.1
  get_storage: ^2.0.3
  lottie: ^1.0.0
  numberpicker: ^2.1.1
  sms_autofill: ^2.3.0
  country_calling_code_picker: ^2.0.1
  package_info_plus: ^3.0.2
  linkfy_text: ^1.1.5
  url_launcher: ^6.1.7
  file_picker: ^5.2.4
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^4.2.1
  provider: ^6.0.1
  connectivity_plus: ^3.0.4
  google_fonts: ^2.0.0
  metrix_plugin: ^1.5.0
  contacts_service: ^0.6.3
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  cached_network_image: ^3.2.3
  toast: ^0.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/images/
    - assets/chat_images/
    - assets/chat_icons/
    - assets/json/themes/
    - assets/json/lotties/
    - assets/images/chat_bg.png
    - assets/images/login_bg.png
    - assets/images/read_contacts.jpg
    - assets/images/free_sms.png
    - assets/images/free_sms_logo.png
    - assets/images/intro001.png
    - assets/images/intro002.png
    - assets/images/intro003.png
    - assets/images/intro004.png
    - assets/images/sponsor_setting.png
    - assets/images/languages.png
    - assets/images/iran_flag.png
    - assets/images/england_flag.png
    - assets/images/saudi_arabia_flag.png
    - assets/images/germany_flag.png
    - assets/images/spain_flag.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/logo.png"
  android: "sms"
  min_sdk_android: 23