import 'package:flutter/material.dart';
import '../../../../domain/entities/country.dart';

class CountriesSelector extends StatefulWidget {
  final Function countrySelectionCallback;
  const CountriesSelector(this.countrySelectionCallback, {Key? key}) : super(key: key);

  @override
  _CountriesSelectorState createState() => _CountriesSelectorState();
}

class _CountriesSelectorState extends State<CountriesSelector> {
  String? _selectedCountryPhoneCode = '98';
  String? _selectedCountryName = 'Iran';

  final List<Country> _countries = [
    Country(name: 'Afghanistan', phoneCode: '93'),
    Country(name: 'Albania', phoneCode: '355'),
    Country(name: 'Algeria', phoneCode: '213'),
    Country(name: 'American Samoa', phoneCode: '1-684'),
    Country(name: 'Andorra', phoneCode: '376'),
    Country(name: 'Angola', phoneCode: '244'),
    Country(name: 'Anguilla', phoneCode: '1-264'),
    Country(name: 'Antigua and Barbuda', phoneCode: '1-268'),
    Country(name: 'Argentina', phoneCode: '54'),
    Country(name: 'Armenia', phoneCode: '374'),
    Country(name: 'Aruba', phoneCode: '297'),
    Country(name: 'Australia', phoneCode: '61'),
    Country(name: 'Austria', phoneCode: '43'),
    Country(name: 'Azerbaijan', phoneCode: '994'),
    Country(name: 'Bahamas', phoneCode: '1-242'),
    Country(name: 'Bahrain', phoneCode: '973'),
    Country(name: 'Bangladesh', phoneCode: '880'),
    Country(name: 'Barbados', phoneCode: '1-246'),
    Country(name: 'Belarus', phoneCode: '375'),
    Country(name: 'Belgium', phoneCode: '32'),
    Country(name: 'Belize', phoneCode: '501'),
    Country(name: 'Benin', phoneCode: '229'),
    Country(name: 'Bermuda', phoneCode: '1-441'),
    Country(name: 'Bhutan', phoneCode: '975'),
    Country(name: 'Bolivia', phoneCode: '591'),
    Country(name: 'Bonaire, Sint Eustatius and Saba', phoneCode: '599'),
    Country(name: 'Bosnia and Herzegovina', phoneCode: '387'),
    Country(name: 'Botswana', phoneCode: '267'),
    Country(name: 'Brazil', phoneCode: '55'),
    Country(name: 'British Indian Ocean Territory', phoneCode: '246'),
    Country(name: 'British Virgin Islands', phoneCode: '1-284'),
    Country(name: 'Brunei Darussalam', phoneCode: '673'),
    Country(name: 'Bulgaria', phoneCode: '359'),
    Country(name: 'Burkina Faso', phoneCode: '226'),
    Country(name: 'Burundi', phoneCode: '257'),
    Country(name: 'Cambodia', phoneCode: '855'),
    Country(name: 'Cameroon', phoneCode: '237'),
    Country(name: 'Canada', phoneCode: '1'),
    Country(name: 'Cape Verde', phoneCode: '238'),
    Country(name: 'Cayman Islands', phoneCode: '1-345'),
    Country(name: 'Central African Republic', phoneCode: '236'),
    Country(name: 'Chad', phoneCode: '235'),
    Country(name: 'Chile', phoneCode: '56'),
    Country(name: 'China', phoneCode: '86'),
    Country(name: 'Christmas Island', phoneCode: '61'),
    Country(name: 'Cocos Islands', phoneCode: '61'),
    Country(name: 'Colombia', phoneCode: '57'),
    Country(name: 'Comoros', phoneCode: '269'),
    Country(name: 'Cook Islands', phoneCode: '682'),
    Country(name: 'Costa Rica', phoneCode: '506'),
    Country(name: "Côte d'Ivoire", phoneCode: '225'),
    Country(name: 'Croatia', phoneCode: '385'),
    Country(name: 'Cuba', phoneCode: '53'),
    Country(name: 'Curaçao', phoneCode: '599'),
    Country(name: 'Cyprus', phoneCode: '357'),
    Country(name: 'Czech Republic', phoneCode: '420'),
    Country(name: 'Democratic Republic of the Congo', phoneCode: '243'),
    Country(name: 'Denmark', phoneCode: '45'),
    Country(name: 'Djibouti', phoneCode: '253'),
    Country(name: 'Dominica', phoneCode: '1-767'),
    Country(name: 'Dominican Republic', phoneCode: '1-809, 1-829, 1-849'),
    Country(name: 'East Timor', phoneCode: '670'),
    Country(name: 'Ecuador', phoneCode: '593'),
    Country(name: 'Egypt', phoneCode: '20'),
    Country(name: 'El Salvador', phoneCode: '503'),
    Country(name: 'Equatorial Guinea', phoneCode: '240'),
    Country(name: 'Eritrea', phoneCode: '291'),
    Country(name: 'Estonia', phoneCode: '372'),
    Country(name: 'Eswatini', phoneCode: '268'),
    Country(name: 'Ethiopia', phoneCode: '251'),
    Country(name: 'Falkland Islands', phoneCode: '500'),
    Country(name: 'Faroe Islands', phoneCode: '298'),
    Country(name: 'Fiji', phoneCode: '679'),
    Country(name: 'Finland', phoneCode: '358'),
    Country(name: 'France', phoneCode: '33'),
    Country(name: 'French Guiana', phoneCode: '594'),
    Country(name: 'French Polynesia', phoneCode: '689'),
    Country(name: 'Gabon', phoneCode: '241'),
    Country(name: 'Gambia', phoneCode: '220'),
    Country(name: 'Georgia', phoneCode: '995'),
    Country(name: 'Germany', phoneCode: '49'),
    Country(name: 'Ghana', phoneCode: '233'),
    Country(name: 'Gibraltar', phoneCode: '350'),
    Country(name: 'Greece', phoneCode: '30'),
    Country(name: 'Greenland', phoneCode: '299'),
    Country(name: 'Grenada', phoneCode: '1-473'),
    Country(name: 'Guadeloupe', phoneCode: '590'),
    Country(name: 'Guam', phoneCode: '1-671'),
    Country(name: 'Guatemala', phoneCode: '502'),
    Country(name: 'Guernsey', phoneCode: '44-1481'),
    Country(name: 'Guinea', phoneCode: '224'),
    Country(name: 'Guinea-Bissau', phoneCode: '245'),
    Country(name: 'Guyana', phoneCode: '592'),
    Country(name: 'Haiti', phoneCode: '509'),
    Country(name: 'Honduras', phoneCode: '504'),
    Country(name: 'Hong Kong', phoneCode: '852'),
    Country(name: 'Hungary', phoneCode: '36'),
    Country(name: 'Iceland', phoneCode: '354'),
    Country(name: 'India', phoneCode: '91'),
    Country(name: 'Indonesia', phoneCode: '62'),
    Country(name: 'Iran', phoneCode: '98'),
    Country(name: 'Iraq', phoneCode: '964'),
    Country(name: 'Ireland', phoneCode: '353'),
    Country(name: 'Isle of Man', phoneCode: '44-1624'),
    Country(name: 'Israel', phoneCode: '972'),
    Country(name: 'Italy', phoneCode: '39'),
    Country(name: 'Jamaica', phoneCode: '1-876'),
    Country(name: 'Japan', phoneCode: '81'),
    Country(name: 'Jersey', phoneCode: '44-1534'),
    Country(name: 'Jordan', phoneCode: '962'),
    Country(name: 'Kazakhstan', phoneCode: '7'),
    Country(name: 'Kenya', phoneCode: '254'),
    Country(name: 'Kiribati', phoneCode: '686'),
    Country(name: 'Kosovo', phoneCode: '383'),
    Country(name: 'Kuwait', phoneCode: '965'),
    Country(name: 'Kyrgyzstan', phoneCode: '996'),
    Country(name: 'Laos', phoneCode: '856'),
    Country(name: 'Latvia', phoneCode: '371'),
    Country(name: 'Lebanon', phoneCode: '961'),
    Country(name: 'Lesotho', phoneCode: '266'),
    Country(name: 'Liberia', phoneCode: '231'),
    Country(name: 'Libya', phoneCode: '218'),
    Country(name: 'Liechtenstein', phoneCode: '423'),
    Country(name: 'Lithuania', phoneCode: '370'),
    Country(name: 'Luxembourg', phoneCode: '352'),
    Country(name: 'Macau', phoneCode: '853'),
    Country(name: 'Madagascar', phoneCode: '261'),
    Country(name: 'Malawi', phoneCode: '265'),
    Country(name: 'Malaysia', phoneCode: '60'),
    Country(name: 'Maldives', phoneCode: '960'),
    Country(name: 'Mali', phoneCode: '223'),
    Country(name: 'Malta', phoneCode: '356'),
    Country(name: 'Marshall Islands', phoneCode: '692'),
    Country(name: 'Martinique', phoneCode: '596'),
    Country(name: 'Mauritania', phoneCode: '222'),
    Country(name: 'Mauritius', phoneCode: '230'),
    Country(name: 'Mayotte', phoneCode: '262'),
    Country(name: 'Mexico', phoneCode: '52'),
    Country(name: 'Micronesia', phoneCode: '691'),
    Country(name: 'Moldova', phoneCode: '373'),
    Country(name: 'Monaco', phoneCode: '377'),
    Country(name: 'Mongolia', phoneCode: '976'),
    Country(name: 'Montenegro', phoneCode: '382'),
    Country(name: 'Montserrat', phoneCode: '1-664'),
    Country(name: 'Morocco', phoneCode: '212'),
    Country(name: 'Mozambique', phoneCode: '258'),
    Country(name: 'Myanmar', phoneCode: '95'),
    Country(name: 'Namibia', phoneCode: '264'),
    Country(name: 'Nauru', phoneCode: '674'),
    Country(name: 'Nepal', phoneCode: '977'),
    Country(name: 'Netherlands', phoneCode: '31'),
    Country(name: 'New Caledonia', phoneCode: '687'),
    Country(name: 'New Zealand', phoneCode: '64'),
    Country(name: 'Nicaragua', phoneCode: '505'),
    Country(name: 'Niger', phoneCode: '227'),
    Country(name: 'Nigeria', phoneCode: '234'),
    Country(name: 'Niue', phoneCode: '683'),
    Country(name: 'Norfolk Island', phoneCode: '672'),
    Country(name: 'North Korea', phoneCode: '850'),
    Country(name: 'North Macedonia', phoneCode: '389'),
    Country(name: 'Northern Mariana Islands', phoneCode: '1-670'),
    Country(name: 'Norway', phoneCode: '47'),
    Country(name: 'Oman', phoneCode: '968'),
    Country(name: 'Pakistan', phoneCode: '92'),
    Country(name: 'Palau', phoneCode: '680'),
    Country(name: 'Palestine', phoneCode: '970'),
    Country(name: 'Panama', phoneCode: '507'),
    Country(name: 'Papua New Guinea', phoneCode: '675'),
    Country(name: 'Paraguay', phoneCode: '595'),
    Country(name: 'Peru', phoneCode: '51'),
    Country(name: 'Philippines', phoneCode: '63'),
    Country(name: 'Pitcairn Islands', phoneCode: '64'),
    Country(name: 'Poland', phoneCode: '48'),
    Country(name: 'Portugal', phoneCode: '351'),
    Country(name: 'Puerto Rico', phoneCode: '1-787, 1-939'),
    Country(name: 'Qatar', phoneCode: '974'),
    Country(name: 'Réunion', phoneCode: '262'),
    Country(name: 'Romania', phoneCode: '40'),
    Country(name: 'Russia', phoneCode: '7'),
    Country(name: 'Rwanda', phoneCode: '250'),
    Country(name: 'Saint Barthélemy', phoneCode: '590'),
    Country(
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        phoneCode: '290'),
    Country(name: 'Saint Kitts and Nevis', phoneCode: '1-869'),
    Country(name: 'Saint Lucia', phoneCode: '1-758'),
    Country(name: 'Saint Martin', phoneCode: '590'),
    Country(name: 'Saint Pierre and Miquelon', phoneCode: '508'),
    Country(name: 'Saint Vincent and the Grenadines', phoneCode: '1-784'),
    Country(name: 'Samoa', phoneCode: '685'),
    Country(name: 'San Marino', phoneCode: '378'),
    Country(name: 'São Tomé and Príncipe', phoneCode: '239'),
    Country(name: 'Saudi Arabia', phoneCode: '966'),
    Country(name: 'Senegal', phoneCode: '221'),
    Country(name: 'Serbia', phoneCode: '381'),
    Country(name: 'Seychelles', phoneCode: '248'),
    Country(name: 'Sierra Leone', phoneCode: '232'),
    Country(name: 'Singapore', phoneCode: '65'),
    Country(name: 'Sint Maarten', phoneCode: '1-721'),
    Country(name: 'Slovakia', phoneCode: '421'),
    Country(name: 'Slovenia', phoneCode: '386'),
    Country(name: 'Solomon Islands', phoneCode: '677'),
    Country(name: 'Somalia', phoneCode: '252'),
    Country(name: 'South Africa', phoneCode: '27'),
    Country(
        name: 'South Georgia and the South Sandwich Islands',
        phoneCode: '500'),
    Country(name: 'South Korea', phoneCode: '82'),
    Country(name: 'South Sudan', phoneCode: '211'),
    Country(name: 'Spain', phoneCode: '34'),
    Country(name: 'Sri Lanka', phoneCode: '94'),
    Country(name: 'Sudan', phoneCode: '249'),
    Country(name: 'Suriname', phoneCode: '597'),
    Country(name: 'Svalbard and Jan Mayen', phoneCode: '47'),
    Country(name: 'Sweden', phoneCode: '46'),
    Country(name: 'Switzerland', phoneCode: '41'),
    Country(name: 'Syria', phoneCode: '963'),
    Country(name: 'Taiwan', phoneCode: '886'),
    Country(name: 'Tajikistan', phoneCode: '992'),
    Country(name: 'Tanzania', phoneCode: '255'),
    Country(name: 'Thailand', phoneCode: '66'),
    Country(name: 'Timor-Leste', phoneCode: '670'),
    Country(name: 'Togo', phoneCode: '228'),
    Country(name: 'Tokelau', phoneCode: '690'),
    Country(name: 'Tonga', phoneCode: '676'),
    Country(name: 'Trinidad and Tobago', phoneCode: '1-868'),
    Country(name: 'Tunisia', phoneCode: '216'),
    Country(name: 'Turkey', phoneCode: '90'),
    Country(name: 'Turkmenistan', phoneCode: '993'),
    Country(name: 'Turks and Caicos Islands', phoneCode: '1-649'),
    Country(name: 'Tuvalu', phoneCode: '688'),
    Country(name: 'Uganda', phoneCode: '256'),
    Country(name: 'Ukraine', phoneCode: '380'),
    Country(name: 'United Arab Emirates', phoneCode: '971'),
    Country(name: 'United Kingdom', phoneCode: '44'),
    Country(name: 'United States', phoneCode: '1'),
    Country(name: 'United States Minor Outlying Islands', phoneCode: '246'),
    Country(name: 'Uruguay', phoneCode: '598'),
    Country(name: 'Uzbekistan', phoneCode: '998'),
    Country(name: 'Vanuatu', phoneCode: '678'),
    Country(name: 'Venezuela', phoneCode: '58'),
    Country(name: 'Vietnam', phoneCode: '84'),
    Country(name: 'Virgin Islands (British)', phoneCode: '1-284'),
    Country(name: 'Virgin Islands (U.S.)', phoneCode: '1-340'),
    Country(name: 'Wallis and Futuna', phoneCode: '681'),
    Country(name: 'Western Sahara', phoneCode: '212'),
    Country(name: 'Yemen', phoneCode: '967'),
    Country(name: 'Zambia', phoneCode: '260'),
    Country(name: 'Zimbabwe', phoneCode: '263'),
  ];

  @override
  void initState() {
    super.initState();
    widget.countrySelectionCallback(_selectedCountryPhoneCode);
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      isExpanded: true,
      value: _selectedCountryName,
      decoration: InputDecoration(
        contentPadding: const EdgeInsets.only(top: 0, bottom: 0, right: 4, left: 4),
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderSide: BorderSide.none,
          borderRadius: BorderRadius.circular(12.0),
        ),
      ),
      items: _countries.map((country) {
        return DropdownMenuItem<String>(
          value: country.name,
          child: Text(
            country.name,
            overflow: TextOverflow.ellipsis,
          ),
          // child: Text('${country.name} (${country.phoneCode})'),
        );
      }).toList(),
      onChanged: (value) {
        setState(() {
          _selectedCountryName = value;
          widget.countrySelectionCallback((_countries.firstWhere((country) => country.name == value)).phoneCode);
        });
      },
    );
  }
}
